Repository hariom20singh/data-structure-, pull requests merged in 2022-10, with the labels that each got.

#4 Hacktoberfest 2022
  circular_linklist000001.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#5 added programs mentioned in the issues
  binarysearch.java
  linked-list.java
Labels: hacktoberfest-accepted

#7 Basic Ops on SLL (Add, Delete, Search, Sort, Prnt)
  Singly_LinkedList.java
Labels: hacktoberfest-accepted

#8 Hacktoberfest 2022
  DOUBLE_linklist008703.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#9 Binary Search Algorithm
  BinarySearch.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#13 CompareLinkedList.c
  CompareLinkedList.c
Labels: Hacktoberfest 2022, hacktoberfest-accepted

#15 HeapSort.cpp
  HeapSort.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted

#14 BinaryTree.cpp
  BinaryTree.cpp
Labels: hacktoberfest-accepted

#17 InterpolationSearch.cpp
  InterpolationSearch.cpp
Labels: Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#16 RadixSort.cpp
  RadixSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#19 DSA Knapsack problem
  knapsack.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#18 BitonicSort.cpp
  BitonicSort.cpp
  PigeonholeSort.c
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#21 ExponentialSearch.cpp
  ExponentialSearch.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#20 AVLtree.cpp
  AVLtree.cpp
Labels: Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#22 Create Linked_list_merge_sort.java
  Linked_list_merge_sort.java
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#24 Container with most water
  Container with most water
Labels: hacktoberfest-accepted

#23 palindrome Number.cpp
  palindrome Number.cpp
Labels: hacktoberfest-accepted

#30 Hacktoberfest 2022
  17.py
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#29 Hacktoberfest 2022
  13.py
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#28 Hacktoberfest 2022
  12.py
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#27 Add files via upload
  5.py
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#26 Add files via upload
  4.py
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#34 Create Stack.cpp
  .gitignore
  Stack.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#35 Create factorial.cpp
  factorial.cpp
Labels: hacktoberfest-accepted

#36 Infix to postfix expression using stack in C
  infix_to_postfix.c
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#40 Create DiagonalMatrix.cpp
  DiagonalMatrix.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#39 Algorithm for binary search recursively
  RecursiveBinarySearch.js
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#38 added prims algorithm
  prims.py
Labels: Hacktoberfest 2022, hacktoberfest-accepted

#37 Create fracional_knapsack.py
  fracional_knapsack.py
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#43 Added Dijkstra Algo
  dijsktra.py
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted

#42 Added recursive cpp code for GCD
  gcd_recursive.cpp
Labels: hacktoberfest-accepted

#44 Added Kruskals Algo
  Kruskals.py
Labels: hacktoberfest-accepted

#47 nQueen using Backtracking
  nQueen.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#46 Create Check duplicates in an array.cpp
  Check duplicates in an array.cpp
Labels: hacktoberfest-accepted

#45 Word-break-2 java solution
  Word_Break_II.java
Labels: hacktoberfest-accepted

#50 Hacktoberfest 2022
  8code10200.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#49 Create DSAquetion.cpp
  DSAquetion.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#48 Create reverse_string_using_stack.cpp
  reverse_string_using_stack.cpp
Labels: hacktoberfest-accepted

#51 hactoberfest2022
  basicQueue.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#52 hactoberfest2022
  basic_Poineter.cpp
Labels: Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#59 Array Question Solution
  ArrayQuestion/MaxsumSubarrayKadanesalgo.cpp
  ArrayQuestion/NextPermutation.cpp
  ArrayQuestion/PascalsTriangle.cpp
  ArrayQuestion/PrintAllPermutation.cpp
  ArrayQuestion/SetMatrixZeroes0.cpp
  ArrayQuestion/SetMatrixZeroes1.cpp
  ArrayQuestion/SetMatrixZeroes2.cpp
  ArrayQuestion/Sort012.cpp
  ArrayQuestion/TwoDArray.cpp
  ArrayQuestion/stockBuyandSell.cpp
Labels: Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#58 Hactoberfest2022
  insertAtEnd.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#57 hacktoberfest 2022
  binSearch.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#56 Hacktoberfest 2022
  pattern6.cpp
Labels: Hacktoberfest 2022, hacktoberfest-accepted

#55 Hacktoberfest 2022
  MaximumOccurance.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#54 Hactoberfest 2022
  insertion_sort.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#53 Create DSAquestions.c
  DSAquestions.c
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#61 Adding some array questions
  ArrayQuestion/SubarraySum.cpp
  ArrayQuestion/TrappingRainwater.cpp
  ArrayQuestion/WaveArray.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#63 Hacktoberfest 2022
  linklist_trivresal.c
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#65 Create letter_combinations_of_a_phone_number.py
  letter_combinations_of_a_phone_number.py
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#69 Morris Traversal
  inorderMorrisTraversal.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#68 Moore’s Voting Algorithm
  mooresVotingAlgorithm.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#67 Sudoku Solver
  SudokuSolver.py
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#66 N Queen Problem
  N-Queens.py
Labels: hacktoberfest-accepted

#62 hactoberfest 2022
  eoro.cpp
Labels: hacktoberfest-accepted

#64 Hactoberfest 22
  pointer.c
Labels: hacktoberfest-accepted

#72 Create DSA_linkedlist.cpp
  DSA_linkedlist.cpp
Labels: hacktoberfest-accepted

#74 Hacktoberfest 2022
  2DTarget.cpp
  FindDuplicateOfn+1Int.cpp
Labels: Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#73 Floyd Cycle detection Algorithm
  FloydAlgo.cpp
  NthTermFibonacciSeries.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#71 Hacktoberfest 2022
  lowercaseoruppercase.c
Labels: Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#78 Create Tic-Tac-Toe Game With Python
  Tic-Tac-Toe Game With Python
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#90 hactoberfest2022
  gallu.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#89 Hacktoberfest 2022
  structure_unions_enums.cpp
Labels: hacktoberfest-accepted

#97 Create algorithm
  algorithm
Labels: hacktoberfest-accepted

#98 HackertoberFest 2022
  Kth_Significant_Bit.cpp
Labels: hacktoberfest-accepted

#105 Hacktoberfest-2022
  backtracking.cpp
Labels: hacktoberfest-accepted

#104 this is a two sum problem
  twosum.c
Labels: hacktoberfest-accepted

#103 HACTOBERFEST 2022
  bubble.sort.cpp
Labels: hacktoberfest-accepted

#102 Closest Pair Divide&Conquer
  closest_pair.c
Labels: hacktoberfest-accepted

#100 Create convert decimal to binary.cpp
  convert decimal to binary.cpp
Labels: hacktoberfest-accepted

#99 I have added Rabin_karp Algorithm to this repository.
  Rabin_karp.cpp
Labels: hacktoberfest-accepted

#96 hacktoberfest2022
  aeonvdedn.c
Labels: hacktoberfest-accepted

#95 Create array
  array
Labels: hacktoberfest-accepted

#94 Create dsa
  dsa
Labels: hacktoberfest-accepted

#93 linked list cycle.cpp
  linked list cycle.cpp
Labels: hacktoberfest-accepted

#92 Create dsa for beginner
  dsa for beginner
Labels: hacktoberfest-accepted

#75 Added Leetcode Standard Problem Sudoku Solver
  sudoku_solver.py
Labels: hacktoberfest-accepted

#87 hacktoberfest 2022
  Untitled-1.cpp
Labels: hacktoberfest-accepted

#86 Create palindrome.dart
  palindrome.dart
Labels: hacktoberfest-accepted

#84 aaded spiralmatrix.cpp
  spiralMatrix.cpp
Labels: hacktoberfest-accepted

#83 Longest_Consecutive_Sequence.cpp
  ArrayQuestion/Longest_Consecutive_Sequence.cpp
Labels: hacktoberfest-accepted

#82 two sum.cpp
  Two_sum.cpp
Labels: hacktoberfest-accepted

#81 Find the repeating and missing numbers
  ArrayQuestion/Find_the_repeating_and_missing_no.cpp
Labels: hacktoberfest-accepted

#80 Merge_overlap.cpp
  ArrayQuestion/Merge_Overlapping_Subintervals.cpp
Labels: hacktoberfest-accepted

#79 Update BinarySearch.cpp
  BinarySearch.cpp
Labels: hacktoberfest-accepted

#77 Hacktoberfest 2022
  MinSwapsEleLessThanKTogether.cpp
Labels: hacktoberfest-accepted

#76 Create reverse of array
  reverse of array
Labels: hacktoberfest-accepted

#106 Fibonacci Search
  myFibonacciSearch.cpp
Labels: hacktoberfest-accepted

#133 hactoberfest 2022
  funoverloading.cpp
Labels: Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#132 Hactoberfest2022
  priya.js
Labels: hacktoberfest-accepted

#122 added problem
  kadanes_algorithm.cpp
  rotating_an_Array.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#136 Create Anurupa_hactober
  Anurupa_hactober
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#135 Create 2022_hactoberfest_Anurupa
  2022_hactoberfest_Anurupa
  Anurupa_hactober1
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#134 Write a function to get the intersection point of two Linked Lists
  Get the intersection point of two Linked Lists.c
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#131 Create Heapsort.java
  Heapsort.java
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#130 Create HeapSort.java
  HeapSort.java
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#129 Program for different Binary Tree Traversal
  BinaryTreeTraversal.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#123 This program will sort the stack
  stack_sort.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#124 Prateek 1211 patch 7
  binary search file
  dsa program
  html
  main.cpp
  project 1.html
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#119 HACTOBERFEST 2022
  factorial.cpp
  fibonacci.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#116 Create binary search file DSA
  binary search file DSA
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#117 Hacktoberfest-2022
  Multiple.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#115 Cocktail Sort
  coctailSort.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#113 this is a three sum problem
  Sumthree.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#111 Create max_stack.cpp
  max_stack.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#110 Graph Question
  Disjoint_Set.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022

#108 hacktoberfest2022
  break and continuen.cpp
Labels: Hacktoberfest, Hacktoberfest 2022, hacktoberfest-accepted, hacktoberfest2022
